language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

install:
  - composer install

before_script:
#  - curl -sSfL -o ~/.phpenv/versions/5.4/bin/phpunit https://phar.phpunit.de/phpunit-4.phar
#  - curl -sSfL -o ~/.phpenv/versions/5.5/bin/phpunit https://phar.phpunit.de/phpunit-4.phar
#  - curl -sSfL -o ~/.phpenv/versions/5.6/bin/phpunit https://phar.phpunit.de/phpunit-5.phar
#  - curl -sSfL -o ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
#  - curl -sSfL -o ~/.phpenv/versions/7.1/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
#  - curl -sSfL -o ~/.phpenv/versions/7.2/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
#  - curl -sSfL -o ~/.phpenv/versions/hhvm/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
  - wget -O ~/.phpenv/versions/5.6/bin/phpunit https://phar.phpunit.de/phpunit-5.phar
  - wget -O ~/.phpenv/versions/7.0/bin/phpunit https://phar.phpunit.de/phpunit-6.phar
  - wget -O ~/.phpenv/versions/7.1/bin/phpunit https://phar.phpunit.de/phpunit-7.phar
  - cp ~/.phpenv/versions/7.1/bin/phpunit ~/.phpenv/versions/7.2/bin/phpunit
  - cp ~/.phpenv/versions/7.1/bin/phpunit ~/.phpenv/versions/nightly/bin/phpunit
  - cp ~/.phpenv/versions/7.1/bin/phpunit ~/.phpenv/hhvm/nightly/bin/phpunit

script:
  - phpunit
