language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - hhvm # on Trusty only
  - nightly

install:
  - composer install

script:
  - vendor/bin/phpunit -v

after_success:
  - export CODECOV_TOKEN="a452e120-6ee3-4d5e-898f-08bfd346d38d"
  - bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'
