language: php

env:
  global:
    - PHPUNIT_VERSION="travis"

matrix:
  fast_finish: true
  include:
    - php: 5.4
      env: PHPUNIT_VERSION="^4"
    - php: 5.5
      env: PHPUNIT_VERSION="^4"
    - php: 5.6
      env: PHPUNIT_VERSION="^4"
    - php: 7.0
      env: PHPUNIT_VERSION="^5"
    - php: 7.1
      env: PHPUNIT_VERSION="^5"
    - php: 7.2
      env: PHPUNIT_VERSION="^5"
    - php: hhvm
      env: PHPUNIT_VERSION="^5"
    - php: nightly
      env: PHPUNIT_VERSION="^5"

before_install:
  - travis_retry composer self-update
  - if [[ $PHPUNIT_VERSION != "travis" ]]; then composer require phpunit/phpunit:${PHPUNIT_VERSION}; fi
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/phpunit -v
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
