language: php

php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - hhvm # on Trusty only
  - nightly

before_script:
    - travis_retry composer install
    - travis_retry composer require "phpunit/phpunit:<7" --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
